name: Check GitHub Runner Location

on:
  workflow_dispatch:

jobs:
  check-ip:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Get IP info
        run: curl -s https://ipinfo.io
